# Mạng nơ-ron 1 lớp ẩn

# 1 - Thư viện

Import những thư viện cần thiết 

In [3]:
# Package imports
import numpy as np

# 2 - Mô hình mạng

**Mô hình**:
<img src="images/classification_kiank.png" style="width:600px;height:300px;">

**Các công thức liên quan**:

Với mỗi ví dụ $x^{(i)}$:
$$z^{[1] (i)} =  W^{[1]} x^{(i)} + b^{[1]}$$ 
$$a^{[1] (i)} = \tanh(z^{[1] (i)})$$
$$z^{[2] (i)} = W^{[2]} a^{[1] (i)} + b^{[2]}$$
$$\hat{y}^{(i)} = a^{[2] (i)} = \sigma(z^{ [2] (i)})$$
$$y^{(i)}_{prediction} = \begin{cases} 1 & \mbox{if } a^{[2](i)} > 0.5 \\ 0 & \mbox{otherwise } \end{cases}$$

Hàm chi phí $J$: 
$$J = - \frac{1}{m} \sum\limits_{i = 0}^{m} \large\left(\small y^{(i)}\log\left(a^{[2] (i)}\right) + (1-y^{(i)})\log\left(1- a^{[2] (i)}\right)  \large  \right)$$

## 2.1 - Hàm kích hoạt
- Sigmoid:
$$sigmoid(x) = \frac{1}{1+e^{-x}}$$
- Relu
$$relu(x) = max(x, 0)$$
- Tanh
$$tanh(x)=\frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [4]:
# GRADED FUNCTION: activation
def activation(x, name='sigmoid'):
    """
    Compute the activation function of x

    Arguments:
        x    -- A scalar or numpy array of any size
        name -- type of activation: ReLU, sigmoid (default), tanh

    Return:
        s -- activation(x)
    """
    
    ### START CODE HERE ### 
    if name == 'sigmoid':
        s = 1 / (1 + np.exp(-x))
    elif name == 'relu':
        s = np.maximum(x, 0)
    elif name == 'tanh':
        s = np.tanh(x)
        
    ### END CODE HERE ###
    return s

In [20]:
np.random.seed(2)
x = np.random.randn(2, 3)
print('x = ' + str(x))
print('activation(x) = ' + str(activation(x, 'sigmoid')))

x = [[-0.41675785 -0.05626683 -2.1361961 ]
 [ 1.64027081 -1.79343559 -0.84174737]]
activation(x) = [[0.39729283 0.485937   0.10562821]
 [0.83757178 0.14265203 0.3011669 ]]


## 2.2 - Khởi tạo tham số

In [21]:
# GRADED FUNCTION: initialize_parameters

def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
        n_x -- size of the input layer
        n_h -- size of the hidden layer
        n_y -- size of the output layer
    
    Returns:
        parameters -- python dictionary containing:
            W1 -- weight matrix of shape (n_h, n_x)
            b1 -- bias vector of shape (n_h, 1)
            W2 -- weight matrix of shape (n_y, n_h)
            b2 -- bias vector of shape (n_y, 1)
    """
    np.random.seed(2)
    
    ### START CODE HERE ### 
    W1 = np.random.randn(n_h, n_x)
    b1 = np.zeros(shape=(n_h, 1))
    W2 = np.random.randn(n_y, n_h)
    b2 = np.zeros(shape=(n_y, 1))
    
    parameters = {
        'W1': W1,
        'W2': W2,
        'b1': b1,
        'b2': b2
    }
    ### END CODE HERE ###
    return parameters

In [23]:
n_x, n_h, n_y = 2, 4, 1
parameters = initialize_parameters(n_x, n_h, n_y)
# print("W1 = " + str(parameters["W1"]))
# print("b1 = " + str(parameters["b1"]))
# print("W2 = " + str(parameters["W2"]))
# print("b2 = " + str(parameters["b2"]))

print(parameters)

{'W1': array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809]]), 'W2': array([[-1.05795222, -0.90900761,  0.55145404,  2.29220801]]), 'b1': array([[0.],
       [0.],
       [0.],
       [0.]]), 'b2': array([[0.]])}


## 2.3 - Lan truyền xuôi
Công thức lan truyền xuôi: Với ví dụ $x^{(i)}$:
$$z^{[1] (i)} =  W^{[1]} x^{(i)} + b^{[1]}$$ 
$$a^{[1] (i)} = \tanh(z^{[1] (i)})$$
$$z^{[2] (i)} = W^{[2]} a^{[1] (i)} + b^{[2]}$$
$$\hat{y}^{(i)} = a^{[2] (i)} = \sigma(z^{ [2] (i)})$$

In [26]:
# GRADED FUNCTION: forward_propagation

def forward_propagation(X, parameters):
    """
    Argument:
        X -- input data of size (n_x, m)
        parameters -- python dictionary containing your parameters (output of initialization function)
    
    Returns:
        A2 -- The sigmoid output of the second activation
        cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """
    
    ### START CODE HERE ### 
    W1 = parameters['W1']
    
    Z1 = np.dot(W1, X) + parameters['b1']
    A1 = activation(Z1, name='tanh')
    
    Z2 = np.dot(parameters['W2'], A1) + parameters['b2']
    A2 = activation(Z2)
    
    cache = {
        'Z1' : Z1,
        'Z2' : Z2,
        'A1' : A1,
        'A2' : A2
    }
    
    ### END CODE HERE ###
    
    return A2, cache

In [32]:
np.random.seed(1)
X = np.random.randn(2, 3)

parameters = initialize_parameters(2, 4, 1)

print(X)
A2, cache = forward_propagation(X, parameters)

# tuple
print(A2)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]
[[0.96040685 0.05002626 0.96641487]]


## 2.4 - Hàm chi phí
Công thức hàm chi phí $J$: 
$$J = - \frac{1}{m} \sum\limits_{i = 0}^{m} \large\left(\small y^{(i)}\log\left(a^{[2] (i)}\right) + (1-y^{(i)})\log\left(1- a^{[2] (i)}\right)  \large  \right)$$

In [33]:
# GRADED FUNCTION: compute_cost

def compute_cost(A2, Y):
    """
    Computes the cost given in above equation
    
    Arguments:
        A2 -- The output of the second activation
        Y -- "true" labels vector of shape (1, number of examples)
    
    Returns:
        cost -- cost given in above equation 
    """
    
    ### START CODE HERE ### 
    m = Y.shape[1]
    
    l = Y * np.log(A2) + (1 - Y) * np.log(1 - A2)
    
    cost = (-1/m) * np.sum(l)
    
    ### END CODE HERE ###
    return cost

## 2.5 - Hàm lan truyền ngược

**Công thức lan truyền ngược**:

<img src="images/grad_summary.png" style="width:600px;height:300px;">
    



In [ ]:
# GRADED FUNCTION: backward_propagation

def backward_propagation(parameters, cache, X, Y):
    """
    Arguments:
        parameters -- python dictionary containing our parameters 
        cache -- a dictionary containing "Z1", "A1", "Z2" and "A2".
        X -- input data of shape (n_x, number of examples)
        Y -- "true" labels vector of shape (n_y, number of examples)
    
    Returns:
        grads -- python dictionary containing your gradients with respect to different parameters
    """
    
    ### START CODE HERE ### 
    
    ### END CODE HERE ###

In [ ]:
np.random.seed(1)
X = np.random.randn(2, 5)
Y = np.random.randn(1, 5)
parameters = initialize_parameters(X.shape[0], 4, Y.shape[0])
A2, cache = forward_propagation(X, parameters)

grads = backward_propagation(parameters, cache, X, Y)

print ("dW1 = "+ str(grads["dW1"]))
print ("db1 = "+ str(grads["db1"]))
print ("dW2 = "+ str(grads["dW2"]))
print ("db2 = "+ str(grads["db2"]))

## 2.6 - Hàm cập nhật tham số


In [ ]:
# GRADED FUNCTION: update_parameters

def update_parameters(parameters, grads, learning_rate = 0.5):
    """
    Arguments:
        parameters -- python dictionary containing your parameters 
        grads -- python dictionary containing your gradients 
    
    Returns:
        parameters -- python dictionary containing your updated parameters 
    """
    
    ### START CODE HERE ### 
    
    ### END CODE HERE ###

In [ ]:
np.random.seed(1)
X = np.random.randn(3, 5)
Y = np.random.randn(1, 5)
parameters = initialize_parameters(X.shape[0], 2, Y.shape[0])
A2, cache = forward_propagation(X, parameters)
grads = backward_propagation(parameters, cache, X, Y)

parameters = update_parameters(parameters, grads)

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

## 2.7 - Hàm mô hình
**Các bước thực hiện**:
1. Khởi tạo tham số
2. Tính lan truyền xuôi
3. Tính lan truyền ngược
4. Cập nhật tham số
5. Tính giá trị hàm chi phí

In [ ]:
# GRADED FUNCTION: nn_model

def nn_model(X, Y, n_h, num_iterations = 100):
    """
    Arguments:
        X -- dataset of shape (n_x, number of examples)
        Y -- labels of shape (n_y, number of examples)
        n_h -- size of the hidden layer
        num_iterations -- Number of iterations in gradient descent loop
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to predict.
    """
    
    np.random.seed(3)
    
    ### START CODE HERE ### 
    
    ### END CODE HERE ###

In [ ]:
np.random.seed(1)
X = np.random.randn(3, 5)
Y = np.random.randn(1, 5)

parameters = nn_model(X, Y, n_h=3, num_iterations=21, print_cost=True)

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))